owner: LBPUnion
repo: UnionStatus

sites:
  - name: SCEE - PS4 Server
    url: https://littlebigplanetps3.online.scee.com:10061/LITTLEBIGPLANETPS3_XML
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Playstation_logo_colour.svg/2560px-Playstation_logo_colour.svg.png
    __dangerous__insecure: true
    expectedStatusCodes:
      - 404
  - name: Beacon - Game Server
    url: https://lighthouse.lbpunion.com/LITTLEBIGPLANETPS3_XML/status
    icon: https://beacon.lbpunion.com/logo-color.png
    maxResponseTime: 500
  - name: Beacon - API
    url: https://lighthouse.lbpunion.com/api/v1/status
    icon: https://beacon.lbpunion.com/logo-color.png
    maxResponseTime: 500
  - name: Beacon - Website
    url: https://beacon.lbpunion.com/status
    icon: https://beacon.lbpunion.com/logo-color.png
    maxResponseTime: 500
  - name: PS3 Toolset - Production
    url: https://toolset.lbpunion.com
    https://em-content.zobj.net/source/skype/289/hammer-and-pick_2692-fe0f.png
    maxResponseTime: 500
  - name: LBP Union CrashHelper
    url: https://crashhelper.lbpunion.com
    icon: https://crashhelper.lbpunion.com/favicon.ico
    maxResponseTime: 500
  - name: LBP Union Press Conference CDN
    url: https://cdn.drones.gay
    icon: https://crashhelper.lbpunion.com/favicon.ico
    maxResponseTime: 500
    
assignees:
  - sudokoko

status-website:
  cname: status.lbpunion.com
  theme: ocean
  logoUrl: https://media.discordapp.net/attachments/1045859676098674751/1063652564660404285/Seal_2021.png?width=968&height=904
  name: LBP Union Status
  introTitle: "Real time **LittleBigPlanet™ Online** status data, at your fingertips."
  introMessage: Status monitoring of our in-house Lighthouse services, as well as the official LBP PS4 servers, powered by Upptime. Readily available to track even the smallest outages.
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/lbpunion

commitMessages:
  commitAuthorName: "UnionStatus"
  commitAuthorEmail: "unionstatus-github@kitgaming67.com"
