# Change these first
owner: LBPUnion # Your GitHub organization or username, where this repository lives
repo: UnionStatus # The name of this repository

sites:
  - name: Beacon - Game Server
    url: $LIGHTHOUSE_GAME_SERVER_URL                       # hidden for security
  - name: Beacon - API
    url: $LIGHTHOUSE_API_URL                               # hidden for security
  - name: Beacon - Website
    url: https://beacon.lbpunion.com/status
assignees:
  - sudokoko

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lbpunion.com
  # baseUrl: /your-repo-name
  logoUrl: https://media.discordapp.net/attachments/1045859676098674751/1063652564660404285/Seal_2021.png?width=968&height=904
  name: LBP Union Status
  introTitle: "Real time **Beacon** data, at your fingertips."
  introMessage: Status monitoring of our in-house Lighthouse services, as well as LBP PS4 servers, powered by Upptime.
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/lbpunion

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
