name: Status Change
on: [issue_comment]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Notify
      uses: stegzilla/discord-notify@v4
      with:
        webhook_url: ${{ secrets.NOTIFICATION_DISCORD_WEBHOOK_URL }}
        title: ${{ github.event.issue.title }}
        message: This status incident has been updated. (${{ github.event.issue.id }}) ```${{ github.event.comment.body }}```
        username: Agent Washington (UnionStatus)
        colour: FFA500
        title_url: https://github.com/LBPUnion/UnionStatus/issues/${{ github.event.issue.id }}
