name: Status New
on: [issues]
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Notify
      uses: stegzilla/discord-notify@v4
      with:
        webhook_url: ${{ secrets.NOTIFICATION_DISCORD_WEBHOOK_URL }}
        title: ${{ github.event.issue.title }}
        message: A new status incident has been created. (${{ github.event.issue.id }})
        username: Agent Washington (UnionStatus)
        colour: FFA500
        title_url: https://github.com/LBPUnion/UnionStatus/issues/${{ github.event.issue.id }}
